language: java
jdk:
- oraclejdk11

notifications:
  slack: gridgo:dSkxVIs1DZFv6k6UtTIPoDJr

addons:
  sonarcloud:
    organization: "gridgo" # the key of the org you chose at step #3
    token: $SONAR_TOKEN

after_success:
- mvn clean test jacoco:report sonar:sonar coveralls:report -DrepoToken=$CoverallsRepoToken