language: java
jdk:
- oraclejdk11

install:
  - tar -xzf protobuf-3.7.0.tar.gz
  - pushd protobuf-3.7.0 && ./configure --prefix=/usr && make && sudo make install && popd

notifications:
  slack: gridgo:dSkxVIs1DZFv6k6UtTIPoDJr

addons:
  sonarcloud:
    organization: "gridgo"
    token: $SONAR_TOKEN

after_success:
- mvn clean test jacoco:report sonar:sonar -Dsonar.projectKey=gridgo_gridgo-base coveralls:report -DrepoToken=$CoverallsRepoToken