language: java
jdk:
- oraclejdk11

notifications:
  slack: gridgo:dSkxVIs1DZFv6k6UtTIPoDJr

after_success:
- mvn clean test jacoco:report sonar:sonar -Dsonar.projectKey=gridgo_gridgo-base -Dsonar.organization=gridgo -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN coveralls:report -DrepoToken=$CoverallsRepoToken